<?xml version="1.0"?>
<package format="3">
  <name>lkh3</name>
  <version>3.0.0</version>
  <description>LKH-3 ATSP solver</description>
  <maintainer email="riccardo.enrico97@proton.me">Riccardo Enrico</maintainer>
  <license>GPL-3.0-only</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
